// MTplot - Luciano Ristori 
//
// read file generated by MTconvert and make plots with plotfourier
// 
//

# include "MTpkg.c"

int main(){

  int i,k;
  int sample, retcode;
  int vmin = 0, vmax = 0;
  double fsample, vmean=0., vrms=0.;
  double fourier[NFREQS];
  double fourierror[NFREQS];
  double xmax, sigma,seconds,avgvol;;
  int kchar,nchar;
  int kmin=0, kmax=48;
  int mintone, ntones,isample;

  // check file format - read input file header

  retcode = checkheader();

  if(retcode !=0) {
    fprintf(stderr,"Bad file format\n");
    return 1;
  }

  // infinite loop on file records

  for(i=0; ;++i){

    retcode = readfourier(&isample, &seconds, &avgvol, &fourier[0], &fourierror[0]);

    // EOF or read error
    if(retcode != 0){
      if(retcode == 1)fprintf(stderr,"End of file at record %d\n", i);
      if(retcode == 2)fprintf(stderr,"Read error at recors %d\n", i);
      fprintf(stderr,"vmin  = %d\n", vmin);
      fprintf(stderr,"vmax  = %d\n", vmax);
      fprintf(stderr,"vmean = %.0f\n", vmean/i);
      fprintf(stderr,"vrms  = %.0f\n", sqrt(vrms/i));
      return 0;
    }

    fprintf(stderr,"plotfourier at %.3f s\n",seconds);
    plotfourier(isample,seconds, avgvol, &fourier[0], &fourierror[0],0,NFREQS);
    //if(seconds > 10.) return 0;
  }
}
